import Link from "next/link";

import "./globals.css";

export const metadata = {
  title: "Mahakali Saw Mill - Manufacture of Wooden Packing Material",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Link href="/products">Products</Link> <br />
        <Link href="/products/details">Product Details</Link> <br />
        <Link href="/">Back</Link>
      </body>
    </html>
  );
}
