import Link from "next/link"
import Image from "next/image"
import logo from "../public/logo.webp"
// import {useState, useEffect} from "react"
import "./globals.css"
import "./fonts.css"
import DynamicHeader from "./DynamicHeader"

export const metadata = {
  title: "Mahakali Saw Mill - Manufacture of Wooden Packing Material",
  description: "Generated by create next app",
}

export default function RootLayout({children}) {
  // const [screenWidth, setScreenWidth] = useState(0)

  // useEffect(() => {
  //   const updateScreenWidth = () => setScreenWidth(window.innerWidth)

  //   updateScreenWidth()
  //   window.addEventListener("resize", updateScreenWidth)

  //   return () => window.removeEventListener("resize", updateScreenWidth)
  // }, [])

  return (
    <html lang="en">
      <body>
        <DynamicHeader />
        {/* <header className="mainHeader">
          <div className="logoDiv">
            <Image src={logo} />
          </div>
          <div className="headerContantDiv">
            <h1>Mahakali Saw Mill</h1>
            <hr />
            <div>
              <p>
                <strong>
                  ALL KIND OF TIMBER MERCHANT & WOODEN BOXMANUFACTURERS
                </strong>
              </p>
              <p>
                64/2,Nr. Neal Petroleum, Opp. S.P.RING ROAD BRTS STOP, Odhav,
                Ahmedabad, Gujarat 382415.
              </p>
              <p>
                <strong>Phone No: </strong>+91 94278-01136, +91 98240-44536{" "}
                <strong> &nbsp;&nbsp; E-Mail ID: </strong>
                mahakali.odhav@gmail.com
              </p>
            </div>
          </div>
        </header>
        <nav className="mainNavigation">
          <Link href="/">Home</Link>
          <div className="dropdown">
            Our Products
            <div className="dropdown-content">
              <Link href="/products/wooden-pallets">Wooden Pallets</Link>
              <Link href="/products/wooden-boxes">Wooden Boxes</Link>
              <Link href="/products/wooden-crates">Wooden Crates</Link>
            </div>
          </div>
          <Link href="/contact-us">Contact Us</Link>
          <Link href="/enquiry">Enquiry</Link>
        </nav> */}
        <div className="content">{children}</div>
        <hr />
        <footer>
          <div className="footer">
            <div className="four-piller">
              <div className="piller-one">
                <h2 className="first">ABOUT COMPANY</h2>
                <div className="head1">
                  <Image className="footor-logo" src={logo} alt="logo"/>
                </div>
                <p className="company-moto">
                  At Mahakali Saw Mill, <br />
                  We prioritize client satisfaction and strive to exceed
                  expectations by providing customized solutions that perfectly
                  meet your unique needs. Experience the difference of working
                  with a partner dedicated to excellence.
                </p>
              </div>
              <div className="piller-two">
                <h2>OUR PRODUCTS</h2>
                <div>
                  <Link href="/products/wooden-pallets">Wooden Pallets</Link>
                  <Link href="/products/wooden-boxes">Wooden Boxes</Link>
                  <Link href="/products/wooden-crates">Wooden Crates</Link>
                </div>
              </div>
              {/* <div className="piller-three">
								<h2>OUR SERVICES</h2>
								<div>
									<a href="faq">
										Specialty In Heavy Machineries & Pallets
										Packing
									</a>
									<a href="faq">Ispm 15 Heat Treatment</a>
									<a href="faq">Fumigation Treatment</a>
									<a href="faq">
										Vacuum Packing Box & Pallets
									</a>
									<a href="faq">Aluminum Foil</a>
									<a href="faq">Thermocol Sheet</a>
									<a href="faq">Silica Gel</a>
									<a href="faq">Stretch Film Roll</a>
								</div>
							</div> */}
              <div className="piller-four">
                <h2>CONTACT INFORMATION</h2>
                <div>
                  <Link href="/contact-us">
                    64/2, Mahakali Saw mill, <br />
                    Nr. Neal Petroleum, <br />
                    Opp. S.P.RING ROAD BRTS STOP, <br />
                    Odhav, Ahmedabad, <br />
                    Gujarat 382-415 India.
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  )
}
